# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_KEY,NEXT_PUBLIC_AUTH_DOMAIN,NEXT_PUBLIC_PROJECT_ID,NEXT_PUBLIC_STORAGE_BUCKET,NEXT_PUBLIC_SENDER_ID,NEXT_PUBLIC_APP_ID,NEXT_PUBLIC_MEASUREMENT_ID" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"